<a href="https://colab.research.google.com/github/mietekdom/Data-Science/blob/master/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.18.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [5]:
x = np.array([1, 3])
print(x)

[1 3]


In [6]:
type(x)

numpy.ndarray

In [7]:
x.ndim

1

In [8]:
x.shape

(2,)

In [9]:
x.size

2

In [11]:
x.dtype

dtype('int64')

In [13]:
y = np.array([1.3, 2.3, 4.5])

In [14]:
print(y)

[1.3 2.3 4.5]


2D Array

In [20]:
np.array([[1, 2,], [-3, 1]])

array([[ 1,  2],
       [-3,  1]])

In [21]:
z = np.array([[1, 2,], [-3, 1]])
print(z)

[[ 1  2]
 [-3  1]]


In [22]:
z.ndim

2

In [23]:
z.shape

(2, 2)

In [24]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [25]:
x.shape

(2, 3)

3D Array

In [26]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

      [[4, 1, 3],
     [4, 2, 1]]]
     )
print(x)

[[[4 3 1]
  [3 1 2]]

 [[4 1 3]
  [4 2 1]]]


In [27]:
x.ndim

3

In [28]:
x.shape

(2, 2, 3)