<a href="https://colab.research.google.com/github/mietekdom/Data-Science/blob/master/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
np.__version__

'1.18.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [ ]:
x = np.array([1, 3], dtype='float')
print(x)

[1. 3.]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
y = np.array([1.3, 2.3, 4.5])

In [ ]:
print(y)

[1.3 2.3 4.5]


2D Array

In [ ]:
np.array([[1, 2,], [-3, 1]])

array([[ 1,  2],
       [-3,  1]])

In [ ]:
z = np.array([[1, 2,], [-3, 1]])
print(z)

[[ 1  2]
 [-3  1]]


In [ ]:
z.ndim

2

In [ ]:
z.shape

(2, 2)

In [ ]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

3D Array

In [ ]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

      [[4, 1, 3],
     [4, 2, 1]]]
     )
print(x)

[[[4 3 1]
  [3 1 2]]

 [[4 1 3]
  [4 2 1]]]


In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 3)

Array creation


In [ ]:
np.zeros(shape=(4, 10)) #tabela z zerami 4x10

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4, 10), dtype='int') #tabela z zerami 4x10, liczby zmiennoprzecinkow

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5, 5)) #tabela z jedynkami

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3,3), fill_value=4, dtype='int') #tabela fill_value - wstawiamy jaka ma byc liczba

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop=10) #tworzymy tablice od 5 do 10 (ale bez 10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10) #tworzymy tablice od 10 do 100, z krokiem co 10

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=10) #tablica od 0 do 1 z z 10 równo rozłozonymi liczbami

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3,5)) #zamiana rodzaju tablicy

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Posdstawowe operacje na Tablicach

In [ ]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -2, 5, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -2  5  2]


In [ ]:
A + B

array([ 6, -1,  9,  4])

In [ ]:
A / B

array([ 1. , -0.5,  0.8,  1. ])

In [ ]:
A + 3 #dodawanie stałych do tablic

array([6, 4, 7, 5])

In [ ]:
A + B * 3 -B

array([ 9, -3, 14,  6])

Podstawowe funkcje w biblotece Numpay

In [15]:
np.exp(1)

2.718281828459045