<a href="https://colab.research.google.com/github/mietekdom/Data-Science/blob/master/01_knowledge/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
np.__version__

'1.18.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [ ]:
x = np.array([1, 3], dtype='float')
print(x)

[1. 3.]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
y = np.array([1.3, 2.3, 4.5])

In [ ]:
print(y)

[1.3 2.3 4.5]


2D Array

In [ ]:
np.array([[1, 2,], [-3, 1]])

array([[ 1,  2],
       [-3,  1]])

In [ ]:
z = np.array([[1, 2,], [-3, 1]])
print(z)

[[ 1  2]
 [-3  1]]


In [ ]:
z.ndim

2

In [ ]:
z.shape

(2, 2)

In [ ]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

3D Array

In [ ]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

      [[4, 1, 3],
     [4, 2, 1]]]
     )
print(x)

[[[4 3 1]
  [3 1 2]]

 [[4 1 3]
  [4 2 1]]]


In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 3)

Array creation


In [ ]:
np.zeros(shape=(4, 10)) #tabela z zerami 4x10

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4, 10), dtype='int') #tabela z zerami 4x10, liczby zmiennoprzecinkow

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5, 5)) #tabela z jedynkami

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3,3), fill_value=4, dtype='int') #tabela fill_value - wstawiamy jaka ma byc liczba

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop=10) #tworzymy tablice od 5 do 10 (ale bez 10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10) #tworzymy tablice od 10 do 100, z krokiem co 10

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=10) #tablica od 0 do 1 z z 10 równo rozłozonymi liczbami

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3,5)) #zamiana rodzaju tablicy

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Posdstawowe operacje na Tablicach

In [ ]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -2, 5, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -2  5  2]


In [ ]:
A + B

array([ 6, -1,  9,  4])

In [ ]:
A / B

array([ 1. , -0.5,  0.8,  1. ])

In [ ]:
A + 3 #dodawanie stałych do tablic

array([6, 4, 7, 5])

In [ ]:
A + B * 3 -B

array([ 9, -3, 14,  6])

Podstawowe funkcje w biblotece Numpay

In [15]:
np.exp(1) #eksponent

2.718281828459045

In [16]:
np.sqrt(9)

3.0

In [17]:
np.all([2, 3, 1]) #funkcja przechodzi po kazdym elemecie i sprawdza True/False

True

In [18]:
np.any([1, 2, 5]) #sprawdza czy funkcje sa True

True

In [21]:
A = np.random.rand(5)
A

array([0.95377005, 0.09207554, 0.86907053, 0.77967027, 0.34622298])

In [22]:
np.argmax(A) #zwraca która wartośc najwieksza

0

In [23]:
A[np.argmax(A)] #wycinamy ta wartosc najwieksza

0.9537700521101039

In [24]:
np.argmin(A)

1

In [25]:
np.argsort(A) #sortuje wartości

array([1, 4, 3, 2, 0])

In [26]:
np.max(A) #wartośc maxymalna

0.9537700521101039

In [27]:
np.mean(A) #średnia

0.6081618738095812

In [28]:
np.median(A) #mediana

0.7796702732777311

In [29]:
np.std(A) #odchylenie standartowe

0.3322320159024466

Indeksowanie, Wycinanie

In [31]:
A = np.arange(20) #tworzymy tablice
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[ind] - konkretny indeks 
# A[start:stop] - indeksy w zakresach
# A[:stop] - indeksy od poczatku do konkretnej wartośc
# A[start:] - indeksy od konkretnej wartości do końca
# A[[ind, ind]] - konkretne indeksy

In [32]:
A[2]

2

In [34]:
A[4:15]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
A[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [36]:
A[9:]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [38]:
A[[2, 9]]

array([2, 9])

In [39]:
A[-1] #ostatnia wartośc

19

In [40]:
B = A.reshape(4, 5)
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [41]:
B[0] #wycina pierwszy wiersz

array([0, 1, 2, 3, 4])

In [42]:
B[:, 0] # wycina pierwsza kolumne

array([ 0,  5, 10, 15])

In [43]:
B[2, 3] # wycnamy konkretny indeks

13

In [45]:
B[1:3, 1:4] #wycinamy fragment tablicy

array([[ 6,  7,  8],
       [11, 12, 13]])

In [49]:
B[1, 2] = 14
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iteracja po tablicach

In [55]:
for row in B: # iterowanie po tablicy
  print(row[:4])

[0 1 2 3]
[ 5  6 14  8]
[10 11 12 13]
[15 16 17 18]


In [56]:
for item in A.flat: #iterujemy po kazdej wartości (wyplaszczajac tablice (flat))
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmiaru tablicy

In [ ]:
A.reshape(5, 4) #zmiana kształtu tablicy

In [60]:
A.ravel() # wyplaszczanie tablicy

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [59]:
B.T #tarnsponowanie tablicy (tak samo jak macierze)

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski Logiczne

In [61]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [62]:
A > 0 #zwraca maske logiczna gdzie mamy wartości dodatnie

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [63]:
A[A > 0] #wycina wartości wieksze od 0

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [64]:
np.bitwise_and(A > -5, A < 5) # zwraca oba warunki

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [67]:
A[np.bitwise_and(A > -5, A < 5)] #wycinanie warunku

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [68]:
np.bitwise_or(A < -5, A > 5) # zwraca warunki dla funkcji or

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])