<a href="https://colab.research.google.com/github/mietekdom/Data-Science/blob/master/01_knowledge/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


Długość wektora

In [ ]:
v1 = np.array([-1, 4]) #tworzymy wektor w numpy array
v1

array([-1,  4])

In [ ]:
np.linalg.norm(v1) # długość wektora 2D

4.123105625617661

In [ ]:
v2 = np.array([-10, 10, 12])
np.linalg.norm(v2) # długość wektora 3D

18.547236990991408

Odlegośc punktów na **płaszczyżnie**

In [ ]:
p = np.array([3, 4])
q = np.array([5, 6])

np.linalg.norm(p - q) 

2.8284271247461903

Odległość dwóch punktów w przestrzeni

In [ ]:
p = np.array([3, 4, 1])
q = np.array([5, 6, 2])
np.linalg.norm(p - q)

3.0

Mnożenie macierzy



In [ ]:
X = np.array([[2, 3], [3, 9]])
Y = np.array([[1], [3]])
print(X)
print(Y)

[[2 3]
 [3 9]]
[[1]
 [3]]


In [ ]:
Z = np.dot(X, Y)
Z

array([[11],
       [30]])

In [ ]:
Z.shape

(2, 1)

In [ ]:
X = np.array([[2, 3, -1], [3, 9, 2]])
Y = np.array([[1, -3, 2], [3, 4, 1], [2, 5, 3]])
print(X, '\n')
print(Y)

[[ 2  3 -1]
 [ 3  9  2]] 

[[ 1 -3  2]
 [ 3  4  1]
 [ 2  5  3]]


In [ ]:
Z = np.dot(X, Y)
Z

array([[ 9,  1,  4],
       [34, 37, 21]])

Wyznacznik macierzy

In [3]:
A = np.array([[2, 4], [-1, 3]])
np.linalg.det(A) # wyznacznik macierzy

9.999999999999998

In [4]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A) #ślad macierzy

5

Macierz jednostkowa

In [5]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Macierz odwrotna

In [9]:
C = np.linalg.inv(A)
C

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

Macierz transponowana

In [10]:
A

array([[ 2,  4],
       [-1,  3]])

In [11]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [ ]:
Rozwiązywanie układu równań

In [12]:
A = np.array([[2, 4], [1, -1]])
A

array([[ 2,  4],
       [ 1, -1]])

In [13]:
B = np.array([[10], [-1]])
B

array([[10],
       [-1]])

In [14]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [15]:
X.shape

(2, 1)