<a href="https://colab.research.google.com/github/mietekdom/Data-Science/blob/master/01_knowledge/03_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'1.18.5'

In [ ]:
Funkcje statystyczne

In [ ]:
price = np.array([[12.4, 12.6, 12.7, 12.8, 10000],
                  [12.3, 12.5, 12.6, 12.1, 20000],
                  [12.5, 12.2, 12.1, 12.4, 15000]])
print(price)

[[1.24e+01 1.26e+01 1.27e+01 1.28e+01 1.00e+04]
 [1.23e+01 1.25e+01 1.26e+01 1.21e+01 2.00e+04]
 [1.25e+01 1.22e+01 1.21e+01 1.24e+01 1.50e+04]]


Suma

In [ ]:
price.sum() #suma wszystkich elementów w tablicy

45149.2

In [ ]:
price.sum(axis=0) # suma poszczególnych kolumn

array([3.72e+01, 3.73e+01, 3.74e+01, 3.73e+01, 4.50e+04])

In [ ]:
price.sum(axis=1) # suma poszczególnych wiersz

array([10050.5, 20049.5, 15049.2])

In [ ]:
np.sum(price)

45149.2

Minimum

In [ ]:
np.min(price)

12.1

In [ ]:
np.min(price, axis=0) # minimum po kolumnach

array([   12.3,    12.2,    12.1,    12.1, 10000. ])

In [ ]:
np.min(price, axis=1) # minimum po wierszach

array([12.4, 12.1, 12.1])

Mediana

In [ ]:
np.median(price)

12.5

Średnia

In [ ]:
np.mean(price, axis=0)

array([1.24000000e+01, 1.24333333e+01, 1.24666667e+01, 1.24333333e+01,
       1.50000000e+04])

Odchylenie standartowe

In [ ]:
np.std(price, axis=0)

array([8.16496581e-02, 1.69967317e-01, 2.62466929e-01, 2.86744176e-01,
       4.08248290e+03])

Wariancja

In [ ]:
np.var(price, axis=0)

array([6.66666667e-03, 2.88888889e-02, 6.88888889e-02, 8.22222222e-02,
       1.66666667e+07])